name: home_decor
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # Uncomment and configure fonts here if you use any custom fonts
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: assets/fonts/YourFont.ttf

# This section is custom and typically used with a code generator like flutter_gen
# Make sure to include flutter_gen in your dependencies if you're using this
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: app_images.dart
